---

- name: Enable only the necessary repos
  shell: "subscription-manager repos --disable='*' --enable {{ ' --enable='.join(required_yum_repos.allversions) }}"
  tags:
    - rhsm_repos
    - satellite
    - capsule
  register: repos_enabled
  ignore_errors: yes

- when: "{{ repos_enabled.rc != 0 }}"
  name: Register this system to Red Hat
  redhat_subscription:
    state: present
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    pool: "{{ rhsm.pool}}"
    autosubscribe: false
  register: rhsm_register_result
  tags:
    - rhsm_repos
    - satellite


- name: Show if it's all been done correctly
  debug:
    var: rhsm_register_result
  tags:
    - rhsm_repos
    - satellite
    - capsule


- name: Enable only the necessary repos
  when: rhsm_register_result.changed
  shell: "subscription-manager repos --disable='*' --enable {{ ' --enable='.join(required_yum_repos.allversions) }}"
  tags:
    - rhsm_repos
    - satellite
    - capsule

- name: Enable version-specific repos for satellite 6.3
  when: satellite_version_xy in ('6.3',)
  shell: "subscription-manager repos --enable {{ ' --enable='.join(required_yum_repos.sat63) }}"
  tags:
    - rhsm_repos
    - satellite
    - capsule

- name: Enable version-specific repos for satellite 6.4
  when: satellite_version_xy in ('6.4',)
  shell: "subscription-manager repos --enable {{ ' --enable='.join(required_yum_repos.sat64) }}"
  tags:
    - rhsm_repos
    - satellite
    - capsule



